import Foundation
import DittoSwift

/// The app's Ditto configuration, built from the root .env via Env.swift
/// (generated by buildEnv.sh — see the swift README). Value type, Sendable.
struct DatabaseConfig: Sendable, Equatable {
    let databaseID: String
    let developmentToken: String
    let serverURL: String

    /// Returns nil when the generated Env.swift carries empty values
    /// (missing .env) — the app shows a configuration screen, never crashes.
    static func load() -> DatabaseConfig? {
        let config = DatabaseConfig(
            databaseID: Env.DITTO_DATABASE_ID,
            developmentToken: Env.DITTO_DEVELOPMENT_TOKEN,
            serverURL: Env.DITTO_SERVER_URL
        )
        guard !config.databaseID.isEmpty,
              !config.developmentToken.isEmpty,
              !config.serverURL.isEmpty
        else { return nil }
        return config
    }

    /// `nonisolated static` and pure so it is unit-testable without a live
    /// Ditto instance (edge-studio convention).
    nonisolated func makeDittoConfig(persistenceDirectory: URL) throws -> DittoConfig {
        // A bare string with no scheme (e.g. a stray UUID) still yields a
        // non-nil relative URL from URL(string:), which then fails opaquely
        // inside Ditto.open(). Require an absolute http(s)/ws(s) URL with a
        // host so bad config data fails loudly here with a clear message.
        guard let url = URL(string: serverURL),
              let scheme = url.scheme?.lowercased(),
              ["https", "http", "wss", "ws"].contains(scheme),
              let host = url.host, !host.isEmpty
        else {
            throw AppError.error(
                message: "DITTO_SERVER_URL must be an absolute URL like "
                    + "https://<cluster>.cloud.dittolive.app (got: '\(serverURL)')"
            )
        }
        return DittoConfig(
            databaseID: databaseID,
            connect: .server(url: url),
            persistenceDirectory: persistenceDirectory
        )
    }
}

enum AppError: LocalizedError {
    case error(message: String)

    var errorDescription: String? {
        switch self {
        case .error(let message): message
        }
    }
}
